export const TOGGLEFOLLOW_USER_REQUEST = 'TOGGLEFOLLOW_USER_REQUEST'
export const TOGGLEFOLLOW_USER_SUCCESS = 'TOGGLEFOLLOW_USER_SUCCESS'
export const TOGGLEFOLLOW_USER_FAIL = 'TOGGLEFOLLOW_USER_FAIL'
