//create a post
export const CREATE_POST_REQUEST = 'CREATE_POST_REQUEST'
export const CREATE_POST_SUCCESS = 'CREATE_POST_SUCCESS'
export const CREATE_POST_FAIL = 'CREATE_POST_FAIL'

//GET ALL POSTS
export const GET_ALL_POSTS_REQUEST = 'GET_ALL_POSTS_REQUEST'
export const GET_ALL_POSTS_SUCCESS = 'GET_ALL_POSTS_SUCCESS'
export const GET_ALL_POSTS_FAIL = 'GET_ALL_POSTS_FAIL'