export const SET_USER_REQUEST = 'SET_USER_REQUEST'
export const SET_USER_SUCCESS = 'SET_USER_SUCCESS'  
export const SET_USER_FAIL = 'SET_USER_FAIL'  

export const GET_CURRENT_USER_REQUEST = 'GET_CURRENT_USER_REQUEST'
export const GET_CURRENT_USER_SUCCESS = 'GET_CURRENT_USER_SUCCESS'
export const GET_CURRENT_USER_FAIL = 'GET_CURRENT_USER_FAIL'

export const EDIT_USERNAME_REQUEST = 'EDIT_USERNAME_REQUEST'
export const EDIT_USERNAME_SUCCESS = 'EDIT_USERNAME_SUCCESS'
export const EDIT_USERNAME_FAIL = 'EDIT_USERNAME_FAIL'

export const EDIT_PHONE_REQUEST = 'EDIT_PHONE_REQUEST'
export const EDIT_PHONE_SUCCESS = 'EDIT_PHONE_SUCCESS'
export const EDIT_PHONE_FAIL = 'EDIT_PHONE_FAIL'

export const EDIT_BIO_REQUEST = 'EDIT_BIO_REQUEST'
export const EDIT_BIO_SUCCESS = 'EDIT_BIO_SUCCESS'
export const EDIT_BIO_FAIL = 'EDIT_BIO_FAIL'
 
export const EDIT_GENDER_REQUEST = 'EDIT_GENDER_REQUEST'
export const EDIT_GENDER_SUCCESS = 'EDIT_GENDER_SUCCESS'
export const EDIT_GENDER_FAIL = 'EDIT_GENDER_FAIL'

export const ADD_PICTURE_REQUEST = 'ADD_PICTURE_REQUEST'
export const ADD_PICTURE_SUCCESS = 'ADD_PICTURE_SUCCESS'
export const ADD_PICTURE_FAIL = 'ADD_PICTURE_FAIL'

export const EDIT_PROFILE_REQUEST = 'EDIT_PROFILE_REQUEST'
export const EDIT_PROFILE_SUCCESS = 'EDIT_PROFILE_SUCCESS'
export const EDIT_PROFILE_FAIL = 'EDIT_PROFILE_FAIL'

export const GET_EXPLORE_USERS_REQUEST = 'GET_EXPLORE_USERS_REQUEST'
export const GET_EXPLORE_USERS_SUCCESS = 'GET_EXPLORE_USERS_SUCCESS'
export const GET_EXPLORE_USERS_FAIL = 'GET_EXPLORE_USERS_FAIL'